server:
  port: 80
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  redis:
    #数据库索引
    database: 0
    #redis 服务器地址
    host: 43.142.175.137
    #redis 端口
    port: 6379
    #redis 密码 默认为空
    # 链接超时时间
    timeout: 10s
  elasticsearch:
    rest:
      uris: http://43.142.175.137:9200